group: "themurderouscricket"
name: "simcity-3000-ordinances-for-sc4-environment"
version: "1.0.0"
subfolder: "140-ordinances"
dependencies:
- "null-45:custom-ordinance-exemplar-host-dll"
assets:
  - assetId: "tmc-simcity-3000-ordinances-for-sc4-environment"

info:
  summary: "This pack contains a recreation of Environment ordinances from SimCity 3000"
  conflicts: "Only compatible with game version 1.1.641, the Windows digital edition."
  description: |-
     This resource is a small but hopefully useful project which attempts to recreate ordinances from SimCity 3000 for use in SimCity 4.

     SimCity 3000 had a very elaborate system of ordinances, complete with exhaustive descriptions, which provided mayors with an important and powerful city management tool. Half of these ordinances did not make it into SimCity 4 however. Thanks to the ".dll era", it is now possible to recreate these old ordinances and this is what this package is all about.

     As Penultimo from the Tropico series would say "I've got something for you to sign, and no - it's not my raise again!". Unleash the red tape! 

  author: "TheMurderousCricket"
  websites:
    - "https://community.simtropolis.com/files/file/37218-simcity-3000-ordinances-for-sc4-environment/"
  images:
    - https://www.simtropolis.com/objects/screens/monthly_2026_01/enviro.jpg.a62520c0c7262b5efd52af7ca615da09.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2026_01/enviro1.jpg.cb564228e7f347a704b23984ef3cbad2.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2026_01/enviro2.jpg.29a504a8877311141bb630a136667487.jpg

---
assetId: "tmc-simcity-3000-ordinances-for-sc4-environment"
version: "1.0.0"
lastModified: "2026-01-27T09:03:50Z"
url: "https://community.simtropolis.com/files/file/37218-simcity-3000-ordinances-for-sc4-environment/?do=download"
